import type { StoreShape } from "./JsonStore";

/**
 * Coherent seed data.
 *
 * Scenario for the restoration flow:
 * - Asset #1 (FEEDER-1) has TWO open repair tickets (#1 REPAIRING, #2 ARRIVED)
 *   via two fault reports. Restoring one must NOT mark the asset NORMAL and
 *   must NOT release the other crew.
 * - Asset #2 has one open ticket (#3 REPAIRING).
 * - Asset #3 has one already-restored ticket (#4) and is NORMAL.
 * - Crew #1/#2/#3 are BUSY on tickets #1/#2/#3; crew #4 is AVAILABLE.
 */
export const storeSeed: StoreShape = {
  gridAsset: [
    {
      id: 1,
      asset_code: "GA-001",
      asset_type: "OUTAGE",
      feeder_line: "FEEDER-1",
      voltage_level: "10kV",
      location_desc: "建设路东段",
      health_status: "DANGEROUS",
      owner_team_id: 1,
      version: 1,
    },
    {
      id: 2,
      asset_code: "GA-002",
      asset_type: "TRIP",
      feeder_line: "FEEDER-2",
      voltage_level: "10kV",
      location_desc: "人民路段",
      health_status: "DANGEROUS",
      owner_team_id: 3,
      version: 1,
    },
    {
      id: 3,
      asset_code: "GA-003",
      asset_type: "VOLTAGE_LOW",
      feeder_line: "FEEDER-3",
      voltage_level: "380V",
      location_desc: "工业园区",
      health_status: "NORMAL",
      owner_team_id: 4,
      version: 1,
    },
  ],
  faultReport: [
    {
      id: 1,
      reporter_name: "张三",
      phone: "13800000001",
      asset_id: 1,
      fault_type: "OUTAGE",
      address_desc: "建设路10号",
      severity: "HIGH",
      report_channel: "PHONE",
      status: "REPAIRING",
    },
    {
      id: 2,
      reporter_name: "李四",
      phone: "13800000002",
      asset_id: 1,
      fault_type: "TRIP",
      address_desc: "建设路20号",
      severity: "MEDIUM",
      report_channel: "APP",
      status: "ARRIVED",
    },
    {
      id: 3,
      reporter_name: "王五",
      phone: "13800000003",
      asset_id: 2,
      fault_type: "EQUIPMENT_DAMAGE",
      address_desc: "人民路5号",
      severity: "HIGH",
      report_channel: "PHONE",
      status: "REPAIRING",
    },
    {
      id: 4,
      reporter_name: "赵六",
      phone: "13800000004",
      asset_id: 3,
      fault_type: "VOLTAGE_LOW",
      address_desc: "工业园路1号",
      severity: "LOW",
      report_channel: "APP",
      status: "RESTORED",
    },
  ],
  repairTicket: [
    {
      id: 1,
      fault_report_id: 1,
      team_id: 1,
      dispatcher_id: 1,
      priority: "HIGH",
      status: "REPAIRING",
      assigned_at: "2026-10-01T09:00:00Z",
      restored_at: null,
      version: 1,
    },
    {
      id: 2,
      fault_report_id: 2,
      team_id: 2,
      dispatcher_id: 1,
      priority: "MEDIUM",
      status: "ARRIVED",
      assigned_at: "2026-10-01T10:00:00Z",
      restored_at: null,
      version: 1,
    },
    {
      id: 3,
      fault_report_id: 3,
      team_id: 3,
      dispatcher_id: 2,
      priority: "HIGH",
      status: "REPAIRING",
      assigned_at: "2026-10-01T11:00:00Z",
      restored_at: null,
      version: 1,
    },
    {
      id: 4,
      fault_report_id: 4,
      team_id: 4,
      dispatcher_id: 2,
      priority: "LOW",
      status: "RESTORED",
      assigned_at: "2026-09-30T09:00:00Z",
      restored_at: "2026-09-30T15:00:00Z",
      version: 2,
    },
  ],
  crew: [
    {
      id: 1,
      name: "抢修一班",
      leader_id: 101,
      skill_tags: "配电,电缆",
      duty_status: "BUSY",
      current_ticket_id: 1,
      contact_phone: "13900000001",
      version: 1,
    },
    {
      id: 2,
      name: "抢修二班",
      leader_id: 102,
      skill_tags: "配电,架空",
      duty_status: "BUSY",
      current_ticket_id: 2,
      contact_phone: "13900000002",
      version: 1,
    },
    {
      id: 3,
      name: "抢修三班",
      leader_id: 103,
      skill_tags: "配电,设备",
      duty_status: "BUSY",
      current_ticket_id: 3,
      contact_phone: "13900000003",
      version: 1,
    },
    {
      id: 4,
      name: "抢修四班",
      leader_id: 104,
      skill_tags: "配电,低压",
      duty_status: "AVAILABLE",
      current_ticket_id: null,
      contact_phone: "13900000004",
      version: 1,
    },
  ],
  sparePartUsage: [
    {
      id: 1,
      ticket_id: 1,
      part_code: "SP-001",
      part_name: "电缆终端头",
      quantity: 2,
      warehouse_name: "中心仓",
      approved_by: "钱七",
      usage_status: "CONSUMED",
    },
  ],
  ticketRestore: [
    {
      id: 1,
      ticket_id: 4,
      idempotency_key: "ticket:4:restore",
      status: "CONFIRMED",
      restored_at: "2026-09-30T15:00:00Z",
      dispatcher_id: 2,
      result: {
        ticket_status: "RESTORED",
        asset_health: "NORMAL",
        crew_released: true,
      },
      created_at: "2026-09-30T15:00:00Z",
    },
  ],
};
