export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_NOT_RESTORABLE: "TICKET_NOT_RESTORABLE",
  RESTORE_CONFLICT: "RESTORE_CONFLICT",
  IDEMPOTENCY_REPLAYED: "IDEMPOTENCY_REPLAYED",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED"
} as const;

/** 复电结果提示文案（与后端 kind 对齐） */
export const RESTORE_RESULT_TEXT = {
  RESTORED: "复电成功：资产/报修/班组已按当前关联工单联动处置",
  REPLAYED: "重复请求，已沿用首次复电结果",
  CONFLICT: "复电冲突：该工单已由另一位调度员先确认，以下为当前状态"
} as const;
