export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_CONFLICT: "TICKET_CONFLICT",
  TICKET_NOT_RESTORABLE: "TICKET_NOT_RESTORABLE",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  RESTORE_FAILED: "RESTORE_FAILED",
  RESTORE_IDEMPOTENT_CONFLICT: "RESTORE_IDEMPOTENT_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
