export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_NOT_RESTORABLE: "TICKET_NOT_RESTORABLE",
  RESTORE_CONFLICT: "RESTORE_CONFLICT",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  FAULT_REPORT_NOT_FOUND: "FAULT_REPORT_NOT_FOUND",
  IDEMPOTENCY_REPLAYED: "IDEMPOTENCY_REPLAYED",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
